services:
  - type: static
    name: labba-studio
    buildCommand: npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /services
        destination: /services/index.html
      - type: rewrite
        source: /about
        destination: /about/index.html
      - type: rewrite
        source: /contact
        destination: /contact/index.html
      - type: rewrite
        source: /work
        destination: /work/index.html
      - type: rewrite
        source: /blog
        destination: /blog/index.html
      - type: rewrite
        source: /*
        destination: /index.html
